// <auto-generated />
using System;
using Eldoria.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eldoria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260703123537_AddSpellTypeImageAndDescription")]
    partial class AddSpellTypeImageAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseAlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BaseBowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxHp")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("BaseMeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseMovement")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEnemy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNPC")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPlayer")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Portrait")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PortraitFileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseAlternateFormId")
                        .IsUnique()
                        .HasFilter("[BaseAlternateFormId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterDialogSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("DialogActiveColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DialogUnActiveColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterDialogSettings");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SceneDialogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SceneDialogId");

                    b.ToTable("DialogPage");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DialogPageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsNarrator")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("ReadingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("DialogPageId");

                    b.ToTable("DialogPageSection");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.EquippableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectedSpellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BowAttackDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("BowDamageReduction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaxConsumableInventoryModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventoryModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxHpModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxMpModifier")
                        .HasColumnType("int");

                    b.Property<int>("MeleeAttackDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("MeleeDamageReduction")
                        .HasColumnType("int");

                    b.Property<int>("MovementModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SpellDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("SpellDamageReduction")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffectedSpellTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("EquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.IntroPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("PreviewPhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId", "Order")
                        .IsUnique();

                    b.ToTable("IntroPage");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("HpEffect")
                        .HasColumnType("int");

                    b.Property<int>("MpEffect")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("int");

                    b.Property<bool>("IsDown")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAlternateForm")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("MaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("MeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFormId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("JourneyId");

                    b.ToTable("JourneyCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterEquippableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquippableItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquippableItemId");

                    b.HasIndex("JourneyCharacterId");

                    b.ToTable("JourneyCharacterEquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("JourneyCharacterId");

                    b.ToTable("JourneyCharacterItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("JourneyCharacterId", "SpellId")
                        .IsUnique();

                    b.ToTable("JourneyCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("JourneyPlaythroughs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GridUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId");

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("int");

                    b.Property<bool>("IsAlternateForm")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDown")
                        .HasColumnType("bit");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacterItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SceneCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SceneCharacterId");

                    b.ToTable("SceneCharacterItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneDialogs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.Property<int?>("SceneCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SceneProgressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JourneyCharacterId");

                    b.HasIndex("SceneCharacterId");

                    b.HasIndex("SceneProgressId", "JourneyCharacterId")
                        .IsUnique()
                        .HasFilter("[JourneyCharacterId] IS NOT NULL");

                    b.HasIndex("SceneProgressId", "SceneCharacterId")
                        .IsUnique()
                        .HasFilter("[SceneCharacterId] IS NOT NULL");

                    b.ToTable("SceneParticipants", t =>
                        {
                            t.HasCheckConstraint("CK_SceneParticipants_Character", "([JourneyCharacterId] IS NOT NULL AND [SceneCharacterId] IS NULL) OR ([JourneyCharacterId] IS NULL AND [SceneCharacterId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneParticipantTurn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SceneParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("SceneProgressId")
                        .HasColumnType("int");

                    b.Property<int>("TurnPosition")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneParticipantId", "SceneProgressId");

                    b.HasIndex("SceneProgressId", "TurnPosition")
                        .IsUnique();

                    b.ToTable("SceneParticipantTurns");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourneyPlaythroughId")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("SceneProgressStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.HasIndex("JourneyPlaythroughId", "SceneId")
                        .IsUnique();

                    b.ToTable("SceneProgresses");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DamageEffect")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("HealthEffect")
                        .HasColumnType("int");

                    b.Property<bool>("IsRadius")
                        .HasColumnType("bit");

                    b.Property<int?>("MagicEffect")
                        .HasColumnType("int");

                    b.Property<int>("MpCost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("SpellTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TypeName")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("SpellTypes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquippableItemSpell", b =>
                {
                    b.Property<int>("AddedSpellsId")
                        .HasColumnType("int");

                    b.Property<int>("EquippableItemsId")
                        .HasColumnType("int");

                    b.HasKey("AddedSpellsId", "EquippableItemsId");

                    b.HasIndex("EquippableItemsId");

                    b.ToTable("EquippableItemSpells", (string)null);
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "BaseAlternateForm")
                        .WithOne()
                        .HasForeignKey("Eldoria.Core.Entities.Character", "BaseAlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaseAlternateForm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterDialogSettings", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithOne("CharacterDialogSettings")
                        .HasForeignKey("Eldoria.Core.Entities.CharacterDialogSettings", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Spell", "Spell")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneDialog", "SceneDialog")
                        .WithMany("DialogPages")
                        .HasForeignKey("SceneDialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneDialog");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPageSection", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany("DialogPageSections")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eldoria.Core.Entities.DialogPage", "DialogPage")
                        .WithMany("DialogPageSections")
                        .HasForeignKey("DialogPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("DialogPage");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.EquippableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SpellType", "AffectedSpellType")
                        .WithMany("AffectedEquippableItems")
                        .HasForeignKey("AffectedSpellTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("EquippableItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AffectedSpellType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.IntroPage", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("IntroPages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Item", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Journeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "AlternateForm")
                        .WithMany()
                        .HasForeignKey("AlternateFormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("JourneyCharacters")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateForm");

                    b.Navigation("Character");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterEquippableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.EquippableItem", "EquippableItem")
                        .WithMany("JourneyCharacterEquippableItems")
                        .HasForeignKey("EquippableItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany("JourneyCharacterEquippableItems")
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippableItem");

                    b.Navigation("JourneyCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Item", "Item")
                        .WithMany("JourneyCharacterItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany("JourneyCharacterItems")
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("JourneyCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany("JourneyCharacterSpells")
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Spell", "Spell")
                        .WithMany("JourneyCharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JourneyCharacter");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("Playthroughs")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("Scenes")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacterItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Item", "Item")
                        .WithMany("SceneCharacterItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.SceneCharacter", "SceneCharacter")
                        .WithMany("SceneCharacterItems")
                        .HasForeignKey("SceneCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SceneCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneDialogs")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneParticipant", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany("SceneParticipants")
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eldoria.Core.Entities.SceneCharacter", "SceneCharacter")
                        .WithMany("SceneParticipants")
                        .HasForeignKey("SceneCharacterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eldoria.Core.Entities.SceneProgress", "SceneProgress")
                        .WithMany("Participants")
                        .HasForeignKey("SceneProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyCharacter");

                    b.Navigation("SceneCharacter");

                    b.Navigation("SceneProgress");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneParticipantTurn", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneProgress", "SceneProgress")
                        .WithMany("ParticipantTurns")
                        .HasForeignKey("SceneProgressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.SceneParticipant", "SceneParticipant")
                        .WithMany("Turns")
                        .HasForeignKey("SceneParticipantId", "SceneProgressId")
                        .HasPrincipalKey("Id", "SceneProgressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SceneParticipant");

                    b.Navigation("SceneProgress");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneProgress", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythrough", "JourneyPlaythrough")
                        .WithMany("SceneProgressRecords")
                        .HasForeignKey("JourneyPlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("ProgressRecords")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JourneyPlaythrough");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SpellType", "SpellType")
                        .WithMany("Spells")
                        .HasForeignKey("SpellTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Spells")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SpellType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("SpellTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EquippableItemSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("AddedSpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.EquippableItem", null)
                        .WithMany()
                        .HasForeignKey("EquippableItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.Navigation("CharacterDialogSettings")
                        .IsRequired();

                    b.Navigation("CharacterSpells");

                    b.Navigation("DialogPageSections");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.Navigation("DialogPageSections");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.EquippableItem", b =>
                {
                    b.Navigation("JourneyCharacterEquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Item", b =>
                {
                    b.Navigation("JourneyCharacterItems");

                    b.Navigation("SceneCharacterItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.Navigation("IntroPages");

                    b.Navigation("JourneyCharacters");

                    b.Navigation("Playthroughs");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.Navigation("JourneyCharacterEquippableItems");

                    b.Navigation("JourneyCharacterItems");

                    b.Navigation("JourneyCharacterSpells");

                    b.Navigation("SceneParticipants");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.Navigation("SceneProgressRecords");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.Navigation("ProgressRecords");

                    b.Navigation("SceneCharacters");

                    b.Navigation("SceneDialogs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.Navigation("SceneCharacterItems");

                    b.Navigation("SceneParticipants");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.Navigation("DialogPages");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneParticipant", b =>
                {
                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneProgress", b =>
                {
                    b.Navigation("ParticipantTurns");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.Navigation("CharacterSpells");

                    b.Navigation("JourneyCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.Navigation("AffectedEquippableItems");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("EquippableItems");

                    b.Navigation("Items");

                    b.Navigation("Journeys");

                    b.Navigation("SpellTypes");

                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
