// <auto-generated />
using System;
using Eldoria.Infrastructure.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eldoria.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719125657_SyncCurrentDomainModel")]
    partial class SyncCurrentDomainModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseAlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BaseBowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxHp")
                        .HasColumnType("int");

                    b.Property<int>("BaseMaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("BaseMeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("BaseMovement")
                        .HasColumnType("int");

                    b.Property<int>("CharacterType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PortraitFileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PortraitUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BaseAlternateFormId")
                        .IsUnique()
                        .HasFilter("[BaseAlternateFormId] IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterDialogSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<string>("DialogActiveColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DialogInActiveColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterDialogSettings");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("CharacterId", "SpellId")
                        .IsUnique();

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterStatAdjustmentAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentOperation")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterStatType")
                        .HasColumnType("int");

                    b.Property<int>("SceneEventActionId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneEventActionId")
                        .IsUnique();

                    b.ToTable("CharacterStatAdjustmentActions");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("HpEffect")
                        .HasColumnType("int");

                    b.Property<int>("MpEffect")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("ConsumableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SceneDialogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SceneDialogId", "OrderNum")
                        .IsUnique();

                    b.ToTable("DialogPages");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPageSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DialogPageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsNarrator")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNum")
                        .HasColumnType("int");

                    b.Property<string>("ReadingText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("DialogPageId", "OrderNum")
                        .IsUnique();

                    b.ToTable("DialogPageSections");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.EquippableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectedSpellTypeId")
                        .HasColumnType("int");

                    b.Property<int>("BowAttackDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("BowDamageReduction")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("MaxConsumableInventoryModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventoryModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxHpModifier")
                        .HasColumnType("int");

                    b.Property<int>("MaxMpModifier")
                        .HasColumnType("int");

                    b.Property<int>("MeleeAttackDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("MeleeDamageReduction")
                        .HasColumnType("int");

                    b.Property<int>("MovementModifier")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("SpellDamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("SpellDamageReduction")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffectedSpellTypeId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("EquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("SeriesId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInitiallyActive")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("MaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("MeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFormId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("JourneyId", "CharacterId")
                        .IsUnique();

                    b.ToTable("JourneyCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("JourneyCharacterId", "SpellId")
                        .IsUnique();

                    b.ToTable("JourneyCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyIntroPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<string>("PreviewPhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId", "SortOrder")
                        .IsUnique();

                    b.ToTable("JourneyIntroPages");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("JourneyPlaythroughs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("int");

                    b.Property<bool>("IsDown")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAlternateForm")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyPlaythroughId")
                        .HasColumnType("int");

                    b.Property<int>("MaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("MeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFormId")
                        .IsUnique()
                        .HasFilter("[AlternateFormId] IS NOT NULL");

                    b.HasIndex("JourneyCharacterId");

                    b.HasIndex("JourneyPlaythroughId", "JourneyCharacterId")
                        .IsUnique();

                    b.ToTable("JourneyPlaythroughCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("JourneyPlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableItemId");

                    b.HasIndex("JourneyPlaythroughCharacterId");

                    b.ToTable("JourneyPlaythroughCharacterConsumableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterEquippableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquippableItemId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyPlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquippableItemId");

                    b.HasIndex("JourneyPlaythroughCharacterId");

                    b.ToTable("JourneyPlaythroughCharacterEquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JourneyCharacterSpellId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyPlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JourneyCharacterSpellId");

                    b.HasIndex("JourneyPlaythroughCharacterId", "JourneyCharacterSpellId")
                        .IsUnique();

                    b.ToTable("JourneyPlaythroughCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughEventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("JourneyPlaythroughId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("JourneyPlaythroughId", "EventTime");

                    b.ToTable("JourneyPlaythroughEventLogs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("GridUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JourneyId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInitiallyActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("MeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFormId");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SceneId", "CharacterId")
                        .IsUnique();

                    b.ToTable("SceneCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SceneCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("SpellId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellId");

                    b.HasIndex("SceneCharacterId", "SpellId")
                        .IsUnique();

                    b.ToTable("SceneCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneChest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DieSides")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "Name")
                        .IsUnique();

                    b.ToTable("SceneChests", t =>
                        {
                            t.HasCheckConstraint("CK_SceneChests_DieSides", "[DieSides] >= 1");
                        });
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneChestLootEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsumableItemId")
                        .HasColumnType("int");

                    b.Property<int?>("EquippableItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RollMaximum")
                        .HasColumnType("int");

                    b.Property<int>("RollMinimum")
                        .HasColumnType("int");

                    b.Property<int>("SceneChestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableItemId");

                    b.HasIndex("EquippableItemId");

                    b.HasIndex("SceneChestId");

                    b.ToTable("SceneChestLootEntries", t =>
                        {
                            t.HasCheckConstraint("CK_SceneChestLootEntries_Item", "([EquippableItemId] IS NOT NULL AND [ConsumableItemId] IS NULL) OR ([EquippableItemId] IS NULL AND [ConsumableItemId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SceneChestLootEntries_Quantity", "[Quantity] >= 1");

                            t.HasCheckConstraint("CK_SceneChestLootEntries_RollRange", "[RollMinimum] >= 1 AND [RollMaximum] >= [RollMinimum]");
                        });
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SceneId");

                    b.ToTable("SceneDialogs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "SortOrder")
                        .IsUnique();

                    b.ToTable("SceneEvents");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEventAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionTargetType")
                        .HasColumnType("int");

                    b.Property<int>("EventActionType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("SceneEventId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneEventId", "SortOrder")
                        .IsUnique();

                    b.ToTable("SceneEventActions");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneIntroPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewPhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SceneId", "SortOrder")
                        .IsUnique();

                    b.ToTable("SceneIntroPages");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythrough", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentParticipantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JourneyPlaythroughId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<int>("SceneId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentParticipantId");

                    b.HasIndex("SceneId");

                    b.HasIndex("JourneyPlaythroughId", "SceneId")
                        .IsUnique();

                    b.ToTable("ScenePlaythroughs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlternateFormId")
                        .HasColumnType("int");

                    b.Property<int?>("BowAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("CurrentHp")
                        .HasColumnType("int");

                    b.Property<int>("CurrentMp")
                        .HasColumnType("int");

                    b.Property<bool>("IsDead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInAlternateForm")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConsumableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxEquippableInventory")
                        .HasColumnType("int");

                    b.Property<int>("MaxHp")
                        .HasColumnType("int");

                    b.Property<int>("MaxMp")
                        .HasColumnType("int");

                    b.Property<int?>("MeleeAttackDamage")
                        .HasColumnType("int");

                    b.Property<int>("Movement")
                        .HasColumnType("int");

                    b.Property<int>("SceneCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlternateFormId")
                        .IsUnique()
                        .HasFilter("[AlternateFormId] IS NOT NULL");

                    b.HasIndex("SceneCharacterId");

                    b.HasIndex("ScenePlaythroughId", "SceneCharacterId")
                        .IsUnique();

                    b.ToTable("ScenePlaythroughCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterConsumableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsumableItemId")
                        .HasColumnType("int");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("ScenePlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableItemId");

                    b.HasIndex("ScenePlaythroughCharacterId");

                    b.ToTable("ScenePlaythroughCharacterConsumableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterEquippableItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquippableItemId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquippableItemId");

                    b.HasIndex("ScenePlaythroughCharacterId");

                    b.ToTable("ScenePlaythroughCharacterEquippableItems");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterSpell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SceneCharacterSpellId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughCharacterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneCharacterSpellId");

                    b.HasIndex("ScenePlaythroughCharacterId", "SceneCharacterSpellId")
                        .IsUnique();

                    b.ToTable("ScenePlaythroughCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughChest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RolledValue")
                        .HasColumnType("int");

                    b.Property<int>("SceneChestId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughId")
                        .HasColumnType("int");

                    b.Property<int?>("SelectedLootEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SceneChestId");

                    b.HasIndex("SelectedLootEntryId");

                    b.HasIndex("ScenePlaythroughId", "SceneChestId")
                        .IsUnique();

                    b.ToTable("ScenePlaythroughChests");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("ExecutionStatus")
                        .HasColumnType("int");

                    b.Property<int>("SceneEventId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SceneEventId");

                    b.HasIndex("ScenePlaythroughId", "SceneEventId")
                        .IsUnique();

                    b.ToTable("ScenePlaythroughEvents");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JourneyPlaythroughCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantType")
                        .HasColumnType("int");

                    b.Property<int?>("ScenePlaythroughCharacterId")
                        .HasColumnType("int");

                    b.Property<int>("ScenePlaythroughId")
                        .HasColumnType("int");

                    b.Property<int?>("SortOrderWithinType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JourneyPlaythroughCharacterId");

                    b.HasIndex("ScenePlaythroughCharacterId");

                    b.HasIndex("ScenePlaythroughId", "JourneyPlaythroughCharacterId")
                        .IsUnique()
                        .HasFilter("[JourneyPlaythroughCharacterId] IS NOT NULL");

                    b.HasIndex("ScenePlaythroughId", "ScenePlaythroughCharacterId")
                        .IsUnique()
                        .HasFilter("[ScenePlaythroughCharacterId] IS NOT NULL");

                    b.HasIndex("ScenePlaythroughId", "ParticipantType", "SortOrderWithinType")
                        .IsUnique()
                        .HasFilter("[SortOrderWithinType] IS NOT NULL");

                    b.ToTable("ScenePlaythroughParticipants", t =>
                        {
                            t.HasCheckConstraint("CK_ScenePlaythroughParticipants_ActiveOrder", "([IsActive] = 1 AND [SortOrderWithinType] IS NOT NULL) OR ([IsActive] = 0 AND [SortOrderWithinType] IS NULL)");

                            t.HasCheckConstraint("CK_ScenePlaythroughParticipants_Character", "([JourneyPlaythroughCharacterId] IS NOT NULL AND [ScenePlaythroughCharacterId] IS NULL) OR ([JourneyPlaythroughCharacterId] IS NULL AND [ScenePlaythroughCharacterId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DamageEffect")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FileName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("HealthEffect")
                        .HasColumnType("int");

                    b.Property<bool>("IsRadius")
                        .HasColumnType("bit");

                    b.Property<int?>("MagicEffect")
                        .HasColumnType("int");

                    b.Property<int>("MpCost")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("Range")
                        .HasColumnType("int");

                    b.Property<int>("SpellTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpellTypeId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TypeName")
                        .IsUnique();

                    b.ToTable("SpellTypes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EquippableItemSpell", b =>
                {
                    b.Property<int>("AddedSpellsId")
                        .HasColumnType("int");

                    b.Property<int>("EquippableItemsId")
                        .HasColumnType("int");

                    b.HasKey("AddedSpellsId", "EquippableItemsId");

                    b.HasIndex("EquippableItemsId");

                    b.ToTable("EquippableItemSpells", (string)null);
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "BaseAlternateForm")
                        .WithOne()
                        .HasForeignKey("Eldoria.Core.Entities.Character", "BaseAlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseAlternateForm");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterDialogSettings", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithOne("CharacterDialogSettings")
                        .HasForeignKey("Eldoria.Core.Entities.CharacterDialogSettings", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Spell", "Spell")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.CharacterStatAdjustmentAction", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.SceneEventAction", "SceneEventAction")
                        .WithOne("CharacterStatAdjustmentAction")
                        .HasForeignKey("Eldoria.Core.Entities.CharacterStatAdjustmentAction", "SceneEventActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("SceneEventAction");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ConsumableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Items")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneDialog", "SceneDialog")
                        .WithMany("DialogPages")
                        .HasForeignKey("SceneDialogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneDialog");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPageSection", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany("DialogPageSections")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Eldoria.Core.Entities.DialogPage", "DialogPage")
                        .WithMany("DialogPageSections")
                        .HasForeignKey("DialogPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("DialogPage");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.EquippableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SpellType", "AffectedSpellType")
                        .WithMany("AffectedEquippableItems")
                        .HasForeignKey("AffectedSpellTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("EquippableItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AffectedSpellType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Series", "Series")
                        .WithMany("Journeys")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Journeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Series");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "AlternateForm")
                        .WithMany()
                        .HasForeignKey("AlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("JourneyCharacters")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateForm");

                    b.Navigation("Character");

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany("JourneyCharacterSpells")
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Spell", "Spell")
                        .WithMany("JourneyCharacterSpells")
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JourneyCharacter");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyIntroPage", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("IntroPages")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("Playthroughs")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "AlternateForm")
                        .WithOne()
                        .HasForeignKey("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "AlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.JourneyCharacter", "JourneyCharacter")
                        .WithMany()
                        .HasForeignKey("JourneyCharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythrough", "JourneyPlaythrough")
                        .WithMany("JourneyCharacters")
                        .HasForeignKey("JourneyPlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateForm");

                    b.Navigation("JourneyCharacter");

                    b.Navigation("JourneyPlaythrough");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterConsumableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.ConsumableItem", "ConsumableItem")
                        .WithMany()
                        .HasForeignKey("ConsumableItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "JourneyPlaythroughCharacter")
                        .WithMany("ConsumableItems")
                        .HasForeignKey("JourneyPlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableItem");

                    b.Navigation("JourneyPlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterEquippableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.EquippableItem", "EquippableItem")
                        .WithMany()
                        .HasForeignKey("EquippableItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "JourneyPlaythroughCharacter")
                        .WithMany("EquippableItems")
                        .HasForeignKey("JourneyPlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippableItem");

                    b.Navigation("JourneyPlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyCharacterSpell", "JourneyCharacterSpell")
                        .WithMany()
                        .HasForeignKey("JourneyCharacterSpellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "JourneyPlaythroughCharacter")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("JourneyPlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyCharacterSpell");

                    b.Navigation("JourneyPlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughEventLog", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythrough", "JourneyPlaythrough")
                        .WithMany("PlaythroughEventLogs")
                        .HasForeignKey("JourneyPlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyPlaythrough");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Journey", "Journey")
                        .WithMany("Scenes")
                        .HasForeignKey("JourneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Journey");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Character", "AlternateForm")
                        .WithMany()
                        .HasForeignKey("AlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateForm");

                    b.Navigation("Character");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneCharacter", "SceneCharacter")
                        .WithMany("SceneCharacterSpells")
                        .HasForeignKey("SceneCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SceneCharacter");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneChest", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneChests")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneChestLootEntry", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.ConsumableItem", "ConsumableItem")
                        .WithMany()
                        .HasForeignKey("ConsumableItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.EquippableItem", "EquippableItem")
                        .WithMany()
                        .HasForeignKey("EquippableItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.SceneChest", "SceneChest")
                        .WithMany("LootEntries")
                        .HasForeignKey("SceneChestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableItem");

                    b.Navigation("EquippableItem");

                    b.Navigation("SceneChest");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneDialogs")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEvent", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneEvents")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEventAction", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneEvent", "SceneEvent")
                        .WithMany("SceneEventActions")
                        .HasForeignKey("SceneEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneEvent");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneIntroPage", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("SceneIntroPages")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythrough", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughParticipant", "CurrentParticipant")
                        .WithMany()
                        .HasForeignKey("CurrentParticipantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythrough", "JourneyPlaythrough")
                        .WithMany("ScenePlaythroughs")
                        .HasForeignKey("JourneyPlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.Scene", "Scene")
                        .WithMany("ScenePlaythroughs")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentParticipant");

                    b.Navigation("JourneyPlaythrough");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacter", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughCharacter", "AlternateForm")
                        .WithOne()
                        .HasForeignKey("Eldoria.Core.Entities.ScenePlaythroughCharacter", "AlternateFormId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.SceneCharacter", "SceneCharacter")
                        .WithMany()
                        .HasForeignKey("SceneCharacterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythrough", "ScenePlaythrough")
                        .WithMany("SceneCharacters")
                        .HasForeignKey("ScenePlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternateForm");

                    b.Navigation("SceneCharacter");

                    b.Navigation("ScenePlaythrough");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterConsumableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.ConsumableItem", "ConsumableItem")
                        .WithMany()
                        .HasForeignKey("ConsumableItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughCharacter", "ScenePlaythroughCharacter")
                        .WithMany("ConsumableItems")
                        .HasForeignKey("ScenePlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableItem");

                    b.Navigation("ScenePlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterEquippableItem", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.EquippableItem", "EquippableItem")
                        .WithMany()
                        .HasForeignKey("EquippableItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughCharacter", "ScenePlaythroughCharacter")
                        .WithMany("EquippableItems")
                        .HasForeignKey("ScenePlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquippableItem");

                    b.Navigation("ScenePlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacterSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneCharacterSpell", "SceneCharacterSpell")
                        .WithMany()
                        .HasForeignKey("SceneCharacterSpellId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughCharacter", "ScenePlaythroughCharacter")
                        .WithMany("CharacterSpells")
                        .HasForeignKey("ScenePlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneCharacterSpell");

                    b.Navigation("ScenePlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughChest", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneChest", "SceneChest")
                        .WithMany()
                        .HasForeignKey("SceneChestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythrough", "ScenePlaythrough")
                        .WithMany("PlaythroughChests")
                        .HasForeignKey("ScenePlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.SceneChestLootEntry", "SelectedLootEntry")
                        .WithMany()
                        .HasForeignKey("SelectedLootEntryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SceneChest");

                    b.Navigation("ScenePlaythrough");

                    b.Navigation("SelectedLootEntry");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughEvent", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SceneEvent", "SceneEvent")
                        .WithMany()
                        .HasForeignKey("SceneEventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythrough", "ScenePlaythrough")
                        .WithMany("PlaythroughEvents")
                        .HasForeignKey("ScenePlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SceneEvent");

                    b.Navigation("ScenePlaythrough");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughParticipant", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.JourneyPlaythroughCharacter", "JourneyPlaythroughCharacter")
                        .WithMany("SceneParticipants")
                        .HasForeignKey("JourneyPlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythroughCharacter", "ScenePlaythroughCharacter")
                        .WithMany("SceneParticipants")
                        .HasForeignKey("ScenePlaythroughCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Eldoria.Core.Entities.ScenePlaythrough", "ScenePlaythrough")
                        .WithMany("Participants")
                        .HasForeignKey("ScenePlaythroughId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JourneyPlaythroughCharacter");

                    b.Navigation("ScenePlaythrough");

                    b.Navigation("ScenePlaythroughCharacter");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Series", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Series")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.SpellType", "SpellType")
                        .WithMany("Spells")
                        .HasForeignKey("SpellTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("Spells")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SpellType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.User", "User")
                        .WithMany("SpellTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EquippableItemSpell", b =>
                {
                    b.HasOne("Eldoria.Core.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("AddedSpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eldoria.Core.Entities.EquippableItem", null)
                        .WithMany()
                        .HasForeignKey("EquippableItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Character", b =>
                {
                    b.Navigation("CharacterDialogSettings")
                        .IsRequired();

                    b.Navigation("CharacterSpells");

                    b.Navigation("DialogPageSections");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.DialogPage", b =>
                {
                    b.Navigation("DialogPageSections");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Journey", b =>
                {
                    b.Navigation("IntroPages");

                    b.Navigation("JourneyCharacters");

                    b.Navigation("Playthroughs");

                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyCharacter", b =>
                {
                    b.Navigation("JourneyCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythrough", b =>
                {
                    b.Navigation("JourneyCharacters");

                    b.Navigation("PlaythroughEventLogs");

                    b.Navigation("ScenePlaythroughs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.JourneyPlaythroughCharacter", b =>
                {
                    b.Navigation("CharacterSpells");

                    b.Navigation("ConsumableItems");

                    b.Navigation("EquippableItems");

                    b.Navigation("SceneParticipants");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Scene", b =>
                {
                    b.Navigation("SceneCharacters");

                    b.Navigation("SceneChests");

                    b.Navigation("SceneDialogs");

                    b.Navigation("SceneEvents");

                    b.Navigation("SceneIntroPages");

                    b.Navigation("ScenePlaythroughs");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneCharacter", b =>
                {
                    b.Navigation("SceneCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneChest", b =>
                {
                    b.Navigation("LootEntries");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneDialog", b =>
                {
                    b.Navigation("DialogPages");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEvent", b =>
                {
                    b.Navigation("SceneEventActions");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SceneEventAction", b =>
                {
                    b.Navigation("CharacterStatAdjustmentAction");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythrough", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PlaythroughChests");

                    b.Navigation("PlaythroughEvents");

                    b.Navigation("SceneCharacters");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.ScenePlaythroughCharacter", b =>
                {
                    b.Navigation("CharacterSpells");

                    b.Navigation("ConsumableItems");

                    b.Navigation("EquippableItems");

                    b.Navigation("SceneParticipants");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Series", b =>
                {
                    b.Navigation("Journeys");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.Spell", b =>
                {
                    b.Navigation("CharacterSpells");

                    b.Navigation("JourneyCharacterSpells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.SpellType", b =>
                {
                    b.Navigation("AffectedEquippableItems");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("Eldoria.Core.Entities.User", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("EquippableItems");

                    b.Navigation("Items");

                    b.Navigation("Journeys");

                    b.Navigation("Series");

                    b.Navigation("SpellTypes");

                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
