using Eldoria.Core.Entities;
using Eldoria.Core.Interfaces;
using Microsoft.EntityFrameworkCore;

namespace Eldoria.Infrastructure.Db.Repositories
{
    public class JourneyRepository(ApplicationDbContext dbContext)
        : Repository<Journey>(dbContext), IJourneyRepository
    {
        private readonly ApplicationDbContext _dbContext = dbContext;

        public async Task<List<Journey>> GetUsersJourneys(int userId, int skip, int take, CancellationToken ct)
        {
            var query = _dbContext.Journeys
                .AsNoTracking()
                .Where(j => j.UserId == userId);

            return await query
                .OrderBy(j => j.CreatedAt)
                .Skip(skip)
                .Take(take)
                .ToListAsync(ct);
        }

        public async Task<Journey?> GetJourneyWithPlayers(int journeyId, CancellationToken ct)
        {
            return await _dbContext.Journeys
                .AsNoTracking()
                .AsSplitQuery()
                .Include(j => j.Scenes)
                .Include(j => j.IntroPages)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                        .ThenInclude(c => c.CharacterDialogSettings)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                        .ThenInclude(c => c.BaseAlternateForm)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                        .ThenInclude(c => c.BaseAlternateForm)
                            .ThenInclude(c => c.CharacterDialogSettings)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                        .ThenInclude(c => c.CharacterSpells)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.Character)
                        .ThenInclude(c => c.CharacterSpells)
                            .ThenInclude(ch => ch.Spell)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.AlternateForm)
                        .ThenInclude(character => character.CharacterSpells)
                            .ThenInclude(characterSpell => characterSpell.Spell)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.AlternateForm)
                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(j => j.JourneyCharacters)
                    .ThenInclude(jc => jc.JourneyCharacterSpells)
                        .ThenInclude(item => item.Spell)
                            .ThenInclude(spell => spell.SpellType)
                .FirstOrDefaultAsync(j => j.Id == journeyId, ct);
        }

        public Task<Journey?> GetPlaythroughSourceAsync(
            int userId,
            int journeyId,
            CancellationToken ct)
        {
            return _dbContext.Journeys
                .IgnoreQueryFilters()
                .AsNoTrackingWithIdentityResolution()
                .AsSplitQuery()
                .Include(journey => journey.IntroPages)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.Character)
                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.Character)
                        .ThenInclude(character => character.BaseAlternateForm)
                            .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.Character)
                        .ThenInclude(character => character.BaseAlternateForm)
                            .ThenInclude(character => character.CharacterSpells)
                                .ThenInclude(characterSpell => characterSpell.Spell)
                                    .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.Character)
                        .ThenInclude(character => character.CharacterSpells)
                            .ThenInclude(characterSpell => characterSpell.Spell)
                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.AlternateForm)
                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.AlternateForm)
                        .ThenInclude(character => character.CharacterSpells)
                            .ThenInclude(characterSpell => characterSpell.Spell)
                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.JourneyCharacters)
                    .ThenInclude(journeyCharacter => journeyCharacter.JourneyCharacterSpells)
                        .ThenInclude(journeyCharacterSpell => journeyCharacterSpell.Spell)
                            .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.Grid)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneIntroPages)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.Character)
                            .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.Character)
                            .ThenInclude(character => character.BaseAlternateForm)
                                .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.Character)
                            .ThenInclude(character => character.BaseAlternateForm)
                                .ThenInclude(character => character.CharacterSpells)
                                    .ThenInclude(characterSpell => characterSpell.Spell)
                                        .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.Character)
                            .ThenInclude(character => character.CharacterSpells)
                                .ThenInclude(characterSpell => characterSpell.Spell)
                                    .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.AlternateForm)
                            .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.AlternateForm)
                            .ThenInclude(character => character.CharacterSpells)
                                .ThenInclude(characterSpell => characterSpell.Spell)
                                    .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneCharacters)
                        .ThenInclude(sceneCharacter => sceneCharacter.SceneCharacterSpells)
                            .ThenInclude(sceneCharacterSpell => sceneCharacterSpell.Spell)
                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneChests)
                        .ThenInclude(chest => chest.LootEntries)
                            .ThenInclude(lootEntry => lootEntry.ConsumableItem)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneChests)
                        .ThenInclude(chest => chest.LootEntries)
                            .ThenInclude(lootEntry => lootEntry.EquippableItem)
                                .ThenInclude(item => item.AffectedSpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneChests)
                        .ThenInclude(chest => chest.LootEntries)
                            .ThenInclude(lootEntry => lootEntry.EquippableItem)
                                .ThenInclude(item => item.AddedSpells)
                                    .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneDialogs)
                        .ThenInclude(dialog => dialog.DialogPages)
                            .ThenInclude(page => page.DialogPageSections)
                                .ThenInclude(section => section.Character)
                                    .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneDialogs)
                        .ThenInclude(dialog => dialog.DialogPages)
                            .ThenInclude(page => page.DialogPageSections)
                                .ThenInclude(section => section.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneDialogs)
                        .ThenInclude(dialog => dialog.DialogPages)
                            .ThenInclude(page => page.DialogPageSections)
                                .ThenInclude(section => section.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterSpells)
                                            .ThenInclude(characterSpell => characterSpell.Spell)
                                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneDialogs)
                        .ThenInclude(dialog => dialog.DialogPages)
                            .ThenInclude(page => page.DialogPageSections)
                                .ThenInclude(section => section.Character)
                                    .ThenInclude(character => character.CharacterSpells)
                                        .ThenInclude(characterSpell => characterSpell.Spell)
                                            .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterStatAdjustmentAction)
                                .ThenInclude(adjustment => adjustment.Character)
                                    .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterStatAdjustmentAction)
                                .ThenInclude(adjustment => adjustment.Character)
                                    .ThenInclude(character => character.CharacterSpells)
                                        .ThenInclude(characterSpell => characterSpell.Spell)
                                            .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterStatAdjustmentAction)
                                .ThenInclude(adjustment => adjustment.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterStatAdjustmentAction)
                                .ThenInclude(adjustment => adjustment.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterSpells)
                                            .ThenInclude(characterSpell => characterSpell.Spell)
                                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterAddSpellAction)
                                .ThenInclude(addSpell => addSpell.Character)
                                    .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterAddSpellAction)
                                .ThenInclude(addSpell => addSpell.Character)
                                    .ThenInclude(character => character.CharacterSpells)
                                        .ThenInclude(characterSpell => characterSpell.Spell)
                                            .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterAddSpellAction)
                                .ThenInclude(addSpell => addSpell.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterDialogSettings)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterAddSpellAction)
                                .ThenInclude(addSpell => addSpell.Character)
                                    .ThenInclude(character => character.BaseAlternateForm)
                                        .ThenInclude(character => character.CharacterSpells)
                                            .ThenInclude(characterSpell => characterSpell.Spell)
                                                .ThenInclude(spell => spell.SpellType)
                .Include(journey => journey.Scenes)
                    .ThenInclude(scene => scene.SceneEvents)
                        .ThenInclude(sceneEvent => sceneEvent.SceneEventActions)
                            .ThenInclude(action => action.CharacterAddSpellAction)
                                .ThenInclude(addSpell => addSpell.Spell)
                                    .ThenInclude(spell => spell.SpellType)
                .FirstOrDefaultAsync(
                    journey => journey.Id == journeyId && journey.UserId == userId,
                    ct);
        }
    }
}
